name: Cleanup
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch: 

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Check Remaining Rate Limit
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh api rate_limit --jq '.resources.core'
        
      - name: Delete Actual Oldest Runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          REPO="${{ github.repository }}"

          for i in {1..2}; do
            # 1. Get the total count of runs in the repo
            TOTAL_COUNT=$(gh api "repos/$REPO/actions/runs" --jq '.total_count')
            
            if [ "$TOTAL_COUNT" -le 300 ]; then
              break
            fi
            
            echo "--- Iteration $i of 10 ---"
            echo "Total runs in repo: $TOTAL_COUNT"
            
            RUN_IDS=$(gh api "repos/$REPO/actions/runs?per_page=10&sort=created&direction=asc" --jq '.workflow_runs[].id')
            
            if [ -z "$RUN_IDS" ]; then
              echo "No runs found on the oldest page."
              break 
            fi

            # 4. Delete them
            for ID in $RUN_IDS; do
              # echo "Deleting: $ID"
              gh run delete --repo "$REPO" "$ID"
              DELAY=$(awk "BEGIN {print 1 + ($RANDOM % 100) / 100}")
              sleep $DELAY
              echo "DELETED: $ID $DELAY"
            done
          done
          
      - name: Check Remaining Rate Limit
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh api rate_limit --jq '.resources.core'
